apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testing
  name: laravel-example-app
  labels:
    app: laravel
    version: v0.1.0
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - caddy
            - php-fpm
      volumes:
        - name: code-repository
          emptyDir: { }
      initContainers:
        # Setup should be extracted to its own job and push it to s3 or build an image which will be push to
        # cluster registry. For the sake of simplicity we are doing it here.
        - name: repository-setup
          image: kubename/laravel-php73:latest
          envFrom:
            - configMapRef:
                name: laravel-example-config
            - secretRef:
                name: laravel-example-secret
          volumeMounts:
            - mountPath: /code
              name: code-repository
          command: [ "/bin/bash" ]
          args:
            - "-c"
            - |
              git clone https://github.com/laravel/laravel.git /code
              cd /code
              composer global require hirak/prestissimo
              composer install --no-dev
              chown -R www-data:www-data /code
      containers:
        - name: caddy
          image: abiosoft/caddy:no-stats
          volumeMounts:
            - mountPath: /code
              name: code-repository
          envFrom:
            - configMapRef:
                name: laravel-example-config
            - secretRef:
                name: laravel-example-secret
          ports:
            - containerPort: 80
          command: [ "/bin/sh" ]
          args:
            - "-c"
            - |
              cat <<EOF >/etc/Caddyfile
              *:80 {
                  root /code/public
                  fastcgi / php-fpm:9000 php {
                      index index.php
                  }
                  rewrite {
                      to {path} {path}/ /index.php?{query}
                  }
                  gzip
              }
              EOF
              caddy --conf /etc/Caddyfile --log stdout --agree=true
        - name: php-fpm
          image: kubename/laravel-php73:latest
          volumeMounts:
            - mountPath: /code
              name: code-repository
          envFrom:
            - configMapRef:
                name: laravel-example-config
            - secretRef:
                name: laravel-example-secret
          ports:
            - containerPort: 9000



