version: "3.4"

services:
  php-fpm:
    build: docker/php-fpm
    volumes:
      - ./stubs:/code
    depends_on:
      - caddy

  caddy:
    build: docker/caddy
    volumes:
    - ./stubs:/code
    ports:
      - 8080:80
