apiVersion: v1
kind: Service
metadata:
  namespace: testing
  name: laravel-example-service
  labels:
    app: laravel
spec:
  type: LoadBalancer
  selector:
    app: laravel
  ports:
    - port: 80
      targetPort: 80
